name: color_generation
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.0 <4.0.0'
dependencies: 
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  logging: ^1.2.0
  provider: ^6.1.1
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
dev_dependencies: 
  flutter_lints: ^3.0.0
  pubspec_dependency_sorter: ^1.0.4
  solid_lints: ^0.1.4
flutter: 
  uses-material-design: true
